[2023-10-14T12:09:49.947+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.list_files manual__2023-10-14T12:09:49.138227+00:00 [queued]>
[2023-10-14T12:09:49.954+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.list_files manual__2023-10-14T12:09:49.138227+00:00 [queued]>
[2023-10-14T12:09:49.954+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-10-14T12:09:49.954+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-10-14T12:09:49.954+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-10-14T12:09:49.962+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): list_files> on 2023-10-14 12:09:49.138227+00:00
[2023-10-14T12:09:49.967+0000] {standard_task_runner.py:55} INFO - Started process 2519 to run task
[2023-10-14T12:09:49.970+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bigquery_data_load', 'list_files', 'manual__2023-10-14T12:09:49.138227+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_data_load.py', '--cfg-path', '/tmp/tmp2ipcu1v0']
[2023-10-14T12:09:49.972+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask list_files
[2023-10-14T12:09:50.011+0000] {task_command.py:388} INFO - Running <TaskInstance: bigquery_data_load.list_files manual__2023-10-14T12:09:49.138227+00:00 [running]> on host 4c2fe63b7c62
[2023-10-14T12:09:50.052+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Niko
AIRFLOW_CTX_DAG_ID=bigquery_data_load
AIRFLOW_CTX_TASK_ID=list_files
AIRFLOW_CTX_EXECUTION_DATE=2023-10-14T12:09:49.138227+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-14T12:09:49.138227+00:00
[2023-10-14T12:09:50.053+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-14T12:09:50.053+0000] {credentials_provider.py:323} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2023-10-14T12:09:50.429+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery_data_load.py", line 19, in list_objects
    kwargs['ti'].xcom_push(value=storage_objects)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_push() missing 1 required positional argument: 'key'
[2023-10-14T12:09:50.438+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bigquery_data_load, task_id=list_files, execution_date=20231014T120949, start_date=20231014T120949, end_date=20231014T120950
[2023-10-14T12:09:50.448+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 36 for task list_files (xcom_push() missing 1 required positional argument: 'key'; 2519)
[2023-10-14T12:09:50.473+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-10-14T12:09:50.490+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
